# Generated by Django 5.2.11 on 2026-02-18 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('contacts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('deals', '0004_quote_quoteitem_quote_deals_quote_status_f33c56_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('interaction', 'Interacción'), ('task', 'Tarea'), ('deal', 'Negocio'), ('contact', 'Contacto'), ('account', 'Cuenta'), ('document', 'Documento'), ('email', 'Email'), ('notification', 'Notificación'), ('quote', 'Cotización'), ('note', 'Nota'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('system', 'Sistema')], db_index=True, max_length=50)),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado'), ('completed', 'Completado'), ('sent', 'Enviado'), ('received', 'Recibido'), ('opened', 'Abierto'), ('clicked', 'Clic realizado'), ('assigned', 'Asignado'), ('moved', 'Movido'), ('won', 'Ganado'), ('lost', 'Perdido'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('uploaded', 'Subido'), ('downloaded', 'Descargado'), ('called', 'Llamado'), ('met', 'Reunido')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='contacts.contact')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='deals.deal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Timeline',
                'verbose_name_plural': 'Eventos de Timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='timeline_ti_created_575111_idx'), models.Index(fields=['event_type', '-created_at'], name='timeline_ti_event_t_2abeca_idx'), models.Index(fields=['user', '-created_at'], name='timeline_ti_user_id_b31bc9_idx'), models.Index(fields=['account', '-created_at'], name='timeline_ti_account_63707a_idx'), models.Index(fields=['contact', '-created_at'], name='timeline_ti_contact_dbabe6_idx'), models.Index(fields=['deal', '-created_at'], name='timeline_ti_deal_id_df4bbd_idx')],
            },
        ),
    ]
