# Generated by Django 5.2.11 on 2026-02-18 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('contacts', '0001_initial'),
        ('deals', '0002_product_alter_deal_options_deal_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Llamada'), ('meeting', 'Reunión'), ('email', 'Email')], max_length=20)),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha programada')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('outcome', models.TextField(blank=True, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='accounts.account', verbose_name='Empresa')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='contacts.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='deals.deal', verbose_name='Trato relacionado')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10, verbose_name='Dirección')),
                ('call_outcome', models.CharField(blank=True, choices=[('connected', 'Conectado'), ('no_answer', 'Sin respuesta'), ('voicemail', 'Buzón de voz'), ('busy', 'Ocupado')], max_length=20, verbose_name='Resultado de llamada')),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='interactions.interaction')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('in_person', 'Presencial'), ('video', 'Videollamada'), ('phone', 'Telefónica')], max_length=20, verbose_name='Tipo de reunión')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación / Link')),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to='contacts.contact', verbose_name='Asistentes')),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='interactions.interaction')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
            },
        ),
    ]
