# Generated by Django 5.2.11 on 2026-02-18 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('contacts', '0001_initial'),
        ('deals', '0003_alter_deal_options_deal_last_score_update_and_more'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente'), ('internal', 'Interno')], default='outbound', max_length=10, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='summary',
            field=models.CharField(blank=True, help_text='Resumen breve de la interacción', max_length=500, verbose_name='Resumen ejecutivo'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Llamada'), ('meeting', 'Reunión'), ('email', 'Email'), ('note', 'Nota')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['-scheduled_at'], name='interaction_schedul_47ce18_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact', '-scheduled_at'], name='interaction_contact_f21827_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['deal', '-scheduled_at'], name='interaction_deal_id_2d8aea_idx'),
        ),
    ]
