# Generated by Django 5.2.11 on 2026-02-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospección'), ('negotiation', 'Negociación'), ('closed_won', 'Cerrado Ganado'), ('closed_lost', 'Cerrado Perdido')], default='prospecting', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
        ),
    ]
