# Generated by Django 5.2.11 on 2026-02-18 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('sku', models.CharField(help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('service', 'Servicio'), ('consulting', 'Consultoría'), ('subscription', 'Suscripción')], max_length=20, verbose_name='Categoría')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trato', 'verbose_name_plural': 'Tratos'},
        ),
        migrations.AddField(
            model_name='deal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado'),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio al momento del deal (puede diferir del precio actual)', max_digits=15, verbose_name='Precio unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='deals.deal', verbose_name='Trato')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del Trato',
                'verbose_name_plural': 'Productos del Trato',
                'unique_together': {('deal', 'product')},
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ManyToManyField(related_name='deals', through='deals.DealProduct', to='deals.product', verbose_name='Productos'),
        ),
    ]
