# Generated by Django 5.2.11 on 2026-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_product_alter_deal_options_deal_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-lead_score', '-created_at'], 'verbose_name': 'Trato', 'verbose_name_plural': 'Tratos'},
        ),
        migrations.AddField(
            model_name='deal',
            name='last_score_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización de score'),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='Puntuación del lead (0-100) basada en Fit y Engagement', verbose_name='Lead Score'),
        ),
    ]
