# Generated by Django 5.2.11 on 2026-02-18 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('contacts', '0001_initial'),
        ('deals', '0003_alter_deal_options_deal_last_score_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Número de cotización')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('viewed', 'Vista'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=10, verbose_name='Estado')),
                ('payment_terms', models.TextField(default='Pago en 30 días', help_text='Condiciones de pago', verbose_name='Términos de pago')),
                ('delivery_terms', models.TextField(blank=True, help_text='Condiciones de entrega', verbose_name='Términos de entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Tasa de impuesto (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto de impuestos')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto de descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('valid_until', models.DateField(verbose_name='Válida hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Vista el')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada el')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Empresa')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='deals.deal', verbose_name='Trato')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total línea')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.product', verbose_name='Producto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='deals_quote_status_f33c56_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['account'], name='deals_quote_account_7bf3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['deal'], name='deals_quote_deal_id_10e533_idx'),
        ),
    ]
