# Generated by Django 5.2.11 on 2026-02-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('contacts', '0001_initial'),
        ('deals', '0003_alter_deal_options_deal_last_score_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('subject', models.CharField(max_length=500, verbose_name='Asunto')),
                ('body_html', models.TextField(verbose_name='Cuerpo (HTML)')),
                ('body_text', models.TextField(blank=True, verbose_name='Cuerpo (Texto plano)')),
                ('category', models.CharField(choices=[('welcome', 'Bienvenida'), ('follow_up', 'Seguimiento'), ('proposal', 'Propuesta'), ('thank_you', 'Agradecimiento'), ('meeting', 'Reunión'), ('reminder', 'Recordatorio'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('available_variables', models.TextField(default='{{contact_name}}, {{contact_email}}, {{account_name}}, {{user_name}}', help_text='Variables que pueden ser usadas en el template', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Para')),
                ('from_email', models.EmailField(max_length=254, verbose_name='De')),
                ('subject', models.CharField(max_length=500, verbose_name='Asunto')),
                ('body_html', models.TextField(blank=True, verbose_name='Cuerpo HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='Cuerpo texto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('opened', 'Abierto'), ('clicked', 'Click en enlace')], default='pending', max_length=10, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Abierto el')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Click el')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.deal')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='email_templates.emailtemplate')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
